<a href="https://colab.research.google.com/github/kaushikyash02/100Days-ML/blob/main/WorkingWithCSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd

# **1. Read CSV**

In [26]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

## **2. Opening CSV file from URL**

In [27]:
import requests
from io import StringIO

url = ""
headers = headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/137.0.0.0 Safari/537.36"
    )
}

## **3. Sep parameter**

to give the speration delimeter

In [28]:
pd.read_csv('/content/sample_data/california_housing_test.csv', sep = ',',names=[])

Empty DataFrame
Columns: []
Index: [(longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, median_house_value), (-122.050000, 37.370000, 27.000000, 3885.000000, 661.000000, 1537.000000, 606.000000, 6.608500, 344700.000000), (-118.300000, 34.260000, 43.000000, 1510.000000, 310.000000, 809.000000, 277.000000, 3.599000, 176500.000000), (-117.810000, 33.780000, 27.000000, 3589.000000, 507.000000, 1484.000000, 495.000000, 5.793400, 270500.000000), (-118.360000, 33.820000, 28.000000, 67.000000, 15.000000, 49.000000, 11.000000, 6.135900, 330000.000000), (-119.670000, 36.330000, 19.000000, 1241.000000, 244.000000, 850.000000, 237.000000, 2.937500, 81700.000000), (-119.560000, 36.510000, 37.000000, 1018.000000, 213.000000, 663.000000, 204.000000, 1.663500, 67000.000000), (-121.430000, 38.630000, 43.000000, 1009.000000, 225.000000, 604.000000, 218.000000, 1.664100, 67000.000000), (-120.650000, 35.480000, 19.000000, 2310.000000, 471.000000, 1341.000000, 441.000000, 3.225000, 166900.000000), (-122.840000, 38.400000, 15.000000, 3080.000000, 617.000000, 1446.000000, 599.000000, 3.669600, 194400.000000), (-118.020000, 34.080000, 31.000000, 2402.000000, 632.000000, 2830.000000, 603.000000, 2.333300, 164200.000000), (-118.240000, 33.980000, 45.000000, 972.000000, 249.000000, 1288.000000, 261.000000, 2.205400, 125000.000000), (-119.120000, 35.850000, 37.000000, 736.000000, 166.000000, 564.000000, 138.000000, 2.416700, 58300.000000), (-121.930000, 37.250000, 36.000000, 1089.000000, 182.000000, 535.000000, 170.000000, 4.690000, 252600.000000), (-117.030000, 32.970000, 16.000000, 3936.000000, 694.000000, 1935.000000, 659.000000, 4.562500, 231200.000000), (-117.970000, 33.730000, 27.000000, 2097.000000, 325.000000, 1217.000000, 331.000000, 5.712100, 222500.000000), (-117.990000, 33.810000, 42.000000, 161.000000, 40.000000, 157.000000, 50.000000, 2.200000, 153100.000000), (-120.810000, 37.530000, 15.000000, 570.000000, 123.000000, 189.000000, 107.000000, 1.875000, 181300.000000), (-121.200000, 38.690000, 26.000000, 3077.000000, 607.000000, 1603.000000, 595.000000, 2.717400, 137500.000000), (-118.880000, 34.210000, 26.000000, 1590.000000, 196.000000, 654.000000, 199.000000, 6.585100, 300000.000000), (-122.590000, 38.010000, 35.000000, 8814.000000, 1307.000000, 3450.000000, 1258.000000, 6.172400, 414300.000000), (-122.150000, 37.750000, 40.000000, 1445.000000, 256.000000, 849.000000, 255.000000, 3.891300, 126300.000000), (-121.370000, 38.680000, 36.000000, 1775.000000, 296.000000, 937.000000, 305.000000, 3.178600, 83400.000000), (-118.160000, 34.070000, 47.000000, 2994.000000, 543.000000, 1651.000000, 561.000000, 3.864400, 241500.000000), (-122.200000, 37.790000, 45.000000, 2021.000000, 528.000000, 1410.000000, 480.000000, 2.778800, 115400.000000), (-117.280000, 33.280000, 13.000000, 6131.000000, 1040.000000, 4049.000000, 940.000000, 3.815600, 150700.000000), (-118.030000, 34.160000, 36.000000, 1401.000000, 218.000000, 667.000000, 225.000000, 7.161500, 484700.000000), (-122.420000, 37.760000, 52.000000, 3587.000000, 1030.000000, 2259.000000, 979.000000, 2.540300, 250000.000000), (-118.390000, 33.990000, 32.000000, 2612.000000, 418.000000, 1030.000000, 402.000000, 6.603000, 369200.000000), (-118.450000, 34.070000, 19.000000, 4845.000000, 1609.000000, 3751.000000, 1539.000000, 1.583000, 350000.000000), (-118.480000, 34.010000, 30.000000, 3078.000000, 954.000000, 1561.000000, 901.000000, 3.485200, 425000.000000), (-119.350000, 36.330000, 14.000000, 1195.000000, 220.000000, 568.000000, 229.000000, 3.148600, 105600.000000), (-118.300000, 33.910000, 34.000000, 1617.000000, 493.000000, 1530.000000, 500.000000, 2.618200, 172600.000000), (-121.130000, 39.310000, 17.000000, 3442.000000, 705.000000, 1693.000000, 619.000000, 2.810200, 128900.000000), (-118.080000, 34.550000, 5.000000, 16181.000000, 2971.000000, 8152.000000, 2651.000000, 4.523700, 141800.000000), (-118.320000, 33.940000, 38.000000, 1067.000000, 170.000000, 499.000000, 169.000000, 4.638900, 183800.000000), (-118.110000, 34.000000, 33.000000, 2886.000000, 726.000000, 2650.000000, 728.000000, 2.625000, 178700.000000), (-122.530000, 37.970000, 52.000000, 1560.000000, 451.000000, 700.000000, 419.000000, 2.512500, 270800.000000), (-118.020000, 33.920000, 34.000000, 1478.000000, 251.000000, 956.000000, 277.000000, 5.523800, 185300.000000), (-118.050000, 33.930000, 31.000000, 894.000000, 203.000000, 883.000000, 190.000000, 3.677100, 141500.000000), (-119.010000, 34.230000, 11.000000, 5785.000000, 1035.000000, 2760.000000, 985.000000, 4.693000, 232200.000000), (-119.320000, 36.200000, 15.000000, 1562.000000, 275.000000, 961.000000, 287.000000, 3.423100, 83300.000000), (-116.920000, 32.770000, 16.000000, 2770.000000, 406.000000, 1269.000000, 429.000000, 6.678300, 275000.000000), (-118.060000, 34.150000, 37.000000, 1980.000000, 226.000000, 697.000000, 226.000000, 15.000100, 500001.000000), (-117.270000, 34.090000, 36.000000, 848.000000, 186.000000, 737.000000, 169.000000, 0.983800, 79300.000000), (-118.230000, 34.130000, 48.000000, 1308.000000, 286.000000, 835.000000, 294.000000, 4.289100, 214800.000000), (-117.240000, 33.170000, 4.000000, 9998.000000, 1874.000000, 3925.000000, 1672.000000, 4.282600, 237500.000000), (-121.910000, 37.440000, 24.000000, 1212.000000, 251.000000, 799.000000, 242.000000, 5.080800, 212500.000000), (-118.290000, 33.940000, 47.000000, 1782.000000, 338.000000, 1003.000000, 329.000000, 2.539800, 105700.000000), (-121.350000, 38.000000, 6.000000, 1649.000000, 369.000000, 732.000000, 350.000000, 3.423100, 123800.000000), (-117.990000, 33.780000, 19.000000, 7399.000000, 1698.000000, 3554.000000, 1593.000000, 3.104900, 173900.000000), (-120.990000, 37.700000, 14.000000, 9849.000000, 1887.000000, 4356.000000, 1780.000000, 3.587700, 160900.000000), (-119.420000, 35.970000, 21.000000, 554.000000, 121.000000, 426.000000, 122.000000, 2.351600, 47500.000000), (-122.210000, 37.800000, 39.000000, 2003.000000, 500.000000, 1109.000000, 464.000000, 3.068200, 156500.000000), (-118.170000, 33.800000, 26.000000, 1589.000000, 380.000000, 883.000000, 366.000000, 3.531300, 187500.000000), (-117.900000, 34.090000, 39.000000, 1726.000000, 333.000000, 892.000000, 335.000000, 4.340900, 191800.000000), (-117.990000, 33.930000, 36.000000, 1287.000000, 233.000000, 779.000000, 229.000000, 4.852300, 175800.000000), (-121.420000, 38.720000, 10.000000, 3054.000000, 528.000000, 1932.000000, 510.000000, 3.090300, 91900.000000), (-118.770000, 34.260000, 26.000000, 3038.000000, 468.000000, 1825.000000, 468.000000, 5.638500, 196900.000000), (-121.930000, 37.330000, 44.000000, 1449.000000, 291.000000, 676.000000, 282.000000, 3.575000, 292200.000000), (-121.820000, 37.250000, 16.000000, 2650.000000, 600.000000, 1969.000000, 586.000000, 3.946100, 194300.000000), (-122.290000, 37.560000, 36.000000, 805.000000, 140.000000, 445.000000, 139.000000, 5.822100, 289400.000000), (-121.780000, 37.230000, 18.000000, 1747.000000, 317.000000, 1055.000000, 285.000000, 5.898000, 229100.000000), (-118.410000, 34.000000, 35.000000, 1062.000000, 305.000000, 1026.000000, 307.000000, 2.715300, 265500.000000), (-121.670000, 40.870000, 31.000000, 1581.000000, 299.000000, 776.000000, 287.000000, 2.906300, 77800.000000), (-118.000000, 33.920000, 26.000000, 2830.000000, 399.000000, 1204.000000, 404.000000, 6.127300, 289600.000000), (-117.220000, 32.730000, 38.000000, 3966.000000, 768.000000, 1640.000000, 729.000000, 3.840900, 291400.000000), (-121.080000, 37.690000, 19.000000, 6473.000000, 1212.000000, 3559.000000, 1123.000000, 3.224600, 129300.000000), (-117.530000, 33.920000, 12.000000, 2290.000000, 319.000000, 728.000000, 228.000000, 6.156100, 233500.000000), (-117.460000, 34.080000, 18.000000, 3830.000000, 750.000000, 2767.000000, 702.000000, 3.660200, 120700.000000), (-117.970000, 33.860000, 35.000000, 1691.000000, 367.000000, 1265.000000, 378.000000, 3.585500, 174300.000000), (-121.920000, 37.330000, 52.000000, 2125.000000, 382.000000, 930.000000, 387.000000, 5.283100, 299500.000000), (-118.200000, 34.040000, 44.000000, 1582.000000, 544.000000, 1998.000000, 515.000000, 1.688800, 125000.000000), (-118.060000, 33.800000, 22.000000, 1892.000000, 442.000000, 1015.000000, 404.000000, 4.137900, 212500.000000), (-122.050000, 37.360000, 34.000000, 2400.000000, 419.000000, 1017.000000, 384.000000, 4.136900, 316900.000000), (-123.790000, 39.500000, 24.000000, 1421.000000, 291.000000, 588.000000, 274.000000, 2.325000, 157300.000000), (-120.790000, 37.490000, 44.000000, 1186.000000, 225.000000, 687.000000, 234.000000, 3.416700, 160700.000000), (-121.890000, 37.350000, 47.000000, 2879.000000, 631.000000, 2229.000000, 606.000000, 3.259900, 183100.000000), (-118.430000, 34.200000, 29.000000, 3051.000000, 694.000000, 1942.000000, 679.000000, 3.111800, 238100.000000), (-118.750000, 34.170000, 18.000000, 6217.000000, 858.000000, 2703.000000, 834.000000, 6.807500, 325900.000000), (-122.470000, 37.990000, 22.000000, 7274.000000, 1002.000000, 2468.000000, 957.000000, 7.494000, 439200.000000), (-120.690000, 37.400000, 46.000000, 860.000000, 130.000000, 496.000000, 147.000000, 3.516700, 137500.000000), (-118.280000, 34.050000, 44.000000, 968.000000, 384.000000, 1805.000000, 375.000000, 1.480100, 212500.000000), (-118.440000, 34.250000, 35.000000, 1583.000000, 324.000000, 1481.000000, 351.000000, 3.700000, 176000.000000), (-122.050000, 38.260000, 21.000000, 7195.000000, 1416.000000, 3927.000000, 1377.000000, 3.091200, 126300.000000), (-121.990000, 37.350000, 18.000000, 1712.000000, 509.000000, 972.000000, 467.000000, 4.397100, 238900.000000), (-121.020000, 37.680000, 28.000000, 2875.000000, 560.000000, 1608.000000, 558.000000, 3.548900, 106400.000000), (-119.850000, 36.740000, 35.000000, 1191.000000, 190.000000, 537.000000, 182.000000, 3.537500, 96700.000000), (-118.020000, 34.080000, 28.000000, 2769.000000, 631.000000, 2452.000000, 581.000000, 2.607100, 175900.000000), (-123.520000, 41.010000, 17.000000, 1564.000000, 345.000000, 517.000000, 222.000000, 2.154200, 83800.000000), (-122.400000, 37.620000, 44.000000, 1619.000000, 362.000000, 1064.000000, 335.000000, 4.023800, 224200.000000), (-118.130000, 34.150000, 24.000000, 1125.000000, 341.000000, 579.000000, 321.000000, 2.812500, 141700.000000), (-122.000000, 37.980000, 32.000000, 1013.000000, 169.000000, 436.000000, 173.000000, 5.111800, 226900.000000), (-118.450000, 34.250000, 36.000000, 1453.000000, 270.000000, 808.000000, 275.000000, 4.383900, 204600.000000), (-117.500000, 33.870000, 4.000000, 6755.000000, 1017.000000, 2866.000000, 850.000000, 5.049300, 239800.000000), (-122.220000, 37.840000, 50.000000, 2935.000000, 473.000000, 1031.000000, 479.000000, 7.500000, 295200.000000), (-119.820000, 36.640000, 30.000000, 1694.000000, 312.000000, 1008.000000, 321.000000, 2.246600, 96000.000000), (-120.210000, 36.770000, 20.000000, 1745.000000, 348.000000, 1093.000000, 302.000000, 2.319400, 90600.000000), (-120.970000, 38.420000, 16.000000, 1748.000000, 322.000000, 4930.000000, 287.000000, 4.302900, 121900.000000), (-121.190000, 38.870000, 20.000000, 3118.000000, 500.000000, 1405.000000, 519.000000, 6.000000, 209400.000000), ...]

[3001 rows x 0 columns]

## **4. Index_col Parameter**

Conerts any column into Sno. or unique column

In [29]:
pd.read_csv('/content/sample_data/california_housing_test.csv', index_col = 'longitude')

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,,,,,,,,
-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...
-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

## **5. Header Parameter**

coverting the column name to header or at what position header is present

In [30]:
pd.read_csv('/content/sample_data/california_housing_test.csv', header = 0)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

## **6. usecols parameter**

In [31]:
pd.read_csv('/content/sample_data/california_housing_test.csv', usecols =['longitude'])

      longitude
0       -122.05
1       -118.30
2       -117.81
3       -118.36
4       -119.67
...         ...
2995    -119.86
2996    -118.14
2997    -119.70
2998    -117.12
2999    -119.63

[3000 rows x 1 columns]

## **7. Skiprows/nrows parameter**

In [40]:
pd.read_csv('/content/sample_data/california_housing_test.csv',skiprows=[1,2])

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
1,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
2,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
3,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
4,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
...,...,...,...,...,...,...,...,...,...
2993,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2994,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2995,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2996,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2997,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [41]:
pd.read_csv('/content/sample_data/california_housing_test.csv',skiprows=[1,2], nrows = 100)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
1,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
2,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
3,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
4,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
...,...,...,...,...,...,...,...,...,...
95,-120.97,38.42,16.0,1748.0,322.0,4930.0,287.0,4.3029,121900.0
96,-121.19,38.87,20.0,3118.0,500.0,1405.0,519.0,6.0000,209400.0
97,-118.20,33.77,52.0,1375.0,457.0,1089.0,317.0,2.2344,200000.0
98,-118.30,34.02,49.0,2120.0,483.0,1522.0,416.0,1.8500,116800.0
99,-122.23,37.79,43.0,5963.0,1344.0,4367.0,1231.0,2.1917,112800.0

## **8. Encoding parameter**

In [43]:
pd.read_csv('/content/sample_data/california_housing_test.csv',encoding='utf-8')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

## **9. Skip bad lines**

In [45]:
pd.read_csv('/content/sample_data/california_housing_test.csv',skiprows=[1,2], nrows = 100, encoding='utf-8',on_bad_lines='skip') # warn, skip, error by default

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
1,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
2,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
3,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
4,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
...,...,...,...,...,...,...,...,...,...
95,-120.97,38.42,16.0,1748.0,322.0,4930.0,287.0,4.3029,121900.0
96,-121.19,38.87,20.0,3118.0,500.0,1405.0,519.0,6.0000,209400.0
97,-118.20,33.77,52.0,1375.0,457.0,1089.0,317.0,2.2344,200000.0
98,-118.30,34.02,49.0,2120.0,483.0,1522.0,416.0,1.8500,116800.0
99,-122.23,37.79,43.0,5963.0,1344.0,4367.0,1231.0,2.1917,112800.0

## **10. dtypes parameter**

In [48]:
pd.read_csv('/content/sample_data/california_housing_test.csv',dtype={'housing_median_age':int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   int64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 211.1 KB

## **11. Handling Dates**

In [50]:
pd.read_csv('/content/sample_data/california_housing_test.csv', parse_dates=[])

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

## **12. Convtors**

In [55]:
def change(latitude):
    if latitude == 0.0:
        return 0
    else:
        return latitude

pd.read_csv(
    '/content/sample_data/california_housing_test.csv',
    converters={'latitude': change}
)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.370000,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.260000,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.780000,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.820000,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.330000,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.420000,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.060000,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.300000,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.100000,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.420000,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

## **13. na_values parameter**

In [57]:
pd.read_csv('/content/sample_data/california_housing_test.csv',na_values=['33.78'])

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,NaN,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

## **14. Loading a huge dataset in chunks**

In [59]:
df= pd.read_csv('/content/sample_data/california_housing_test.csv',chunksize = 300)

In [64]:
for chunk in df:
  print(type(chunk))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>