<a href="https://colab.research.google.com/github/kaushikyash02/100Days-ML/blob/main/WorkingOnAPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd #1ec8524f35a789ee0a1a1bf591aab8a5

In [5]:
import requests

response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=1ec8524f35a789ee0a1a1bf591aab8a5&language=en-US&page=1')

In [12]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,144.0851,8.960,1795
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,85.8959,8.723,30625
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,375.7553,8.691,2995
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,130.2689,8.690,5380
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,38.1806,8.700,23076

In [15]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [19]:
for i in range(1,100):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    f = pd.concat([df, temp_df], ignore_index=True)

In [21]:
f

,id,title,overview,release_date,popularity,vote_average,vote_count
0,615777,Babylon,A tale of outsized ambition and outrageous exc...,2022-12-22,10.6867,7.347,3792
1,439584,I Can Quit Whenever I Want 3: Ad Honorem,Has been an year since Pietro Zinni's gang got...,2017-11-30,0.4425,7.347,992
2,249164,If I Stay,"Mia Hall, a talented young cellist, thought th...",2014-08-21,3.6445,7.347,4316
3,88273,A Royal Affair,A young queen falls in love with her physician...,2012-03-29,1.7303,7.347,946
4,14447,A Matter of Loaf and Death,"Wallace and Gromit open a bakery, accidentally...",2008-12-26,1.6666,7.349,611
5,14283,The Red Violin,300 years of a remarkable musical instrument. ...,1998-11-13,2.0587,7.347,451
6,3089,Red River,"Following the Civil War, headstrong rancher Th...",1948-09-17,2.7383,7.347,594
7,2252,Eastern Promises,A Russian teenager living in London dies durin...,2007-09-14,4.7251,7.347,3732
8,377,A Nightmare on Elm Street,Teenagers in a small town are dropping like fl...,1984-11-09,9.9201,7.347,5763
9,38528,Horse Fever,"Bruno Fioretti, known as ""Mandrake"", is an inv...",1976-10-29,0.4665,7.346,382
10,377263,Frantz,"In the aftermath of WWI, a young German who gr...",2016-09-07,0.9387,7.345,736
11,271706,Big Fish & Begonia,"Beyond the human realm, there is a magical rac...",2016-07-08,4.4281,7.345,492
12,61791,Rise of the Planet of the Apes,A highly intelligent chimpanzee named Caesar h...,2011-08-03,11.5299,7.345,12793
13,33701,French Fried Vacation 2,In this sequel to Les Bronzes (1978) summer ha...,1979-11-22,0.9988,7.300,1267
14,3110,Shane,A weary gunfighter attempts to settle down wit...,1953-04-23,3.0259,7.345,686
15,2056,The Station Agent,"When his only friend dies, a man born with dwa...",2003-12-05,2.6657,7.345,796
16,1151031,Bring Her Back,"Following the death of their father, a brother...",2025-05-19,9.2954,7.344,1720
17,396263,GANTZ:O,After being brutally murdered in a subway stat...,2016-10-14,4.2264,7.344,845
18,11305,Mystery Train,"In Memphis, Tennessee, over the course of a si...",1989-09-06,1.9727,7.300,507
19,1554,Down by Law,"A disc jockey, a pimp and an Italian tourist e...",1986-09-20,1.5964,7.300,849

In [24]:
f.to_csv('movies.csv')